### ISSUE TITLE
Similaripy package error

### ISSUE THREAD

**Issue by diepngocnhiep** [miferroudjene/RACF#2]
Hi, 

My name is Diep from Erasmus Uni Rotterdam. I am currently working on a thesis as the extension of this paper. I first have to replicate the code. However, the package "similaripy" is only for OS, correct? And I used Windows so now I could not install this with pip. Do you have any recommendation as the alternative for "similaripy" now? It is very important for my thesis and I really appreciate your work. I really hope you could help me. 

Thanks in advance and look forward to your reply.

Kind regards,
Diep

**Comment by miferroudjene** [comment]
Hello @diepngocnhiep,
First of all, Thank your for your concern and support for my implementation.

I was hoping to redirect you to the original implementation of this paper. As there are still some minor improvement that I need to adresse, yet still can't find a convient time busy (maybe I should create a Todo List for that, and be opne for futur Pull requests), be cause if I remmeber correctly at that time the author didn't realise the code (sadly it still the case).

As an answer your question, I'have done the implementation and run the code on Ubuntu OS (Linux), and it was also tested on jupyter notebook ( you could try it by importing the nootbook on Colab Google Platform). Concerning WindowsOS (WOS), I found in "similaripy" package documentaion (https://pypi.org/project/similaripy/) a note that indicate that it was tested under the WOS. Here's the note : 
> This library has been tested with Python 3.6 on Ubuntu, OSX and Windows.
> (Note: on Windows there are problem with flag format_output='csr', just leave it set to the default value 'coo')

My suggestion for you, as a windows user, is to use the Anaconda Python distribution.

Good luck with your thesis  
Don't hesitate to reach me out if needed for futur colaboration,
Mouloud

**Comment by diepngocnhiep** [comment]
Hi,

Thanks for your very detailed answer. I have managed to run the code with the package. It is my Visual Studio was out of date, I have updated and it works very well now.

One small question, in the description you mentioned about the Jupyter Notebook RACF.ipnyb, but I could not find the link to it anywhere, also in the zip file.

Another small contribution, my supervisor for thesis also suggest to change the formula in 3.4 of the paper as swap (1-alpha) and alpha in the exponential of cosine similarity: s(i,j) = p( i | j )^(1-alpha) * p( j | i )^(alpha).

Another thank you for the contribution and the works for implementation. Really appreciate the effort.

Best,
Diep :)

**Comment by miferroudjene** [comment]
I have just pushed it to the main branch, you can check it now.
For the contribution "Swapin the exponential" in cosine formulat, I'dont really see the motivation behind that.
I mean mathematically speaking there is no difference as long as Alpha and Alpha-1 remain in [0 ; 1] range, maybe your supervisor suggested to you that it would be semantically correct if we swipe and in my POV that's not a contribution but an interpretation. 

Please feel free to close this issue, if you have no more question about "Similaripy package error"
